default: -p html_report 
html_report: --format progress --format html --out=./output/features_report.html  --tag 'not @ignore'
json_report: --format json --out=./output/output.json --tag 'not @ignore'
